spring:
  security:
    user:
      password: abc
      name: user
  application:
    name: auth-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
  data:
    mongodb:
      host: localhost
      port: 27017
      username: user
      password: password
      database: metrics

server:
  port: 9000

logging:
  level:
    org.springframework.security: trace