spring:
#  security:
#    user:
#      password: a
#      name: a
  application:
    name: auth-service

  cloud:
    config:
      enabled: false
  #  config:
#    import: configserver:http://localhost:8888
#  cloud:
#    config:
#      fail-fast: false
#      password: ${CONFIG_SERVICE_PASSWORD}
#      username: user
  data:
    mongodb:
      host: localhost
      port: 27017
      username: user
      password: password
      database: metrics

server:
  port: 9000

logging:
  level:
    org.springframework.security: trace