spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks


  application:
    name: statistics-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
  data:
    mongodb:
      host: localhost
      port: 27017
      username: user
      password: password
      database: metrics
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
app:
  properties:
    webclient:
      exchangeClient:
        hostname: 'https://api.exchangeratesapi.io/v1/'
        api: '104d29f18182c45565d04bb9f9f145a8s'
server:
  port: 8084
  address: localhost
logging:
  level:
    reactor:
      netty:
        http:
          client: error



resilience4j:
  circuitbreaker:
    instances:
      exchangeRateService:
        register-health-indicator: true
        sliding-window-size: 2
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 1
        automatic-transition-from-open-to-half-open-enabled: true
