spring:
  application:
    name: account-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
