spring:
  security:
    oauth2:
#      client:
#        registration:
#          stat-service-exchange:
#            provider: spring
#            client-name:
#            client-id:
#            scope:
#              - stat.update
#        provider:
#          spring:
#            issuer-uri: http://localhost:9000

      client:
        registration:

          account-service-client-credentials:
            client-secret: token
            provider: spring
            client-name: account-service-client-credentials
            client-id: account-service
            authorization-grant-type: client_credentials
            scope: message.read,message.write

          account-service-as-stat-service-token-exchange:
            client-id: account-service
            client-name: account-service-as-stat-service-token-exchange
            client-secret: token
            authorization-grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            provider: spring
            scope: message.read,message.write

        provider:
          spring:
            issuer-uri: http://localhost:9000

      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks


  application:
    name: account-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user
  data:
    mongodb:
      host: localhost
      port: 27017
      username: user
      password: password
      database: metrics
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
app:
  properties:
    webclient:
      auth-service:
        name: 'auth-service'
        host: 'http://localhost:8761' # in case of eureka change it to name (used in webclient)
server:
  port: 8083
  address: localhost


