spring:
  application:
    name: client
  main:
    banner-mode: off
  security:
    oauth2:
      client:
        registration:
          account-service-tex-client:
            provider: spring
            client-id: account-service
            client-secret: token
            authorization-grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            client-name: account-service-tex-client
            scope:
              - message.read
              - message.write

          messaging-client-oidc:
            provider: spring
            client-id: backend-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: 'http://127.0.0.1:8080/login/oauth2/code/{registrationId}'
            client-name: messaging-client-oidc
            scope:
              - profile
              - openid


          downstream-client:
            provider: spring
            client-id: backend-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: 'http://127.0.0.1:8080/post-connect'
            client-name: downstream-client
            scope:
              - message.read
              - message.write
          messaging-client-creds-oidc:
            provider: spring
            client-id: backend-client
            client-secret: secret
            authorization-grant-type: client_credentials
            redirect-uri: 'http://127.0.0.1:8080/login/oauth2/code/{registrationId}'
            client-name: messaging-client-creds-oidc
            scope:
              - profile
              - openid
        provider:
          spring:
            issuer-uri: http://localhost:9000

eureka:
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


logging:
  level:
    org.springframework.security: trace
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.springframework.web.reactive.function.client.ExchangeFilterFunction: TRACE
    org.springframework.web.reactive.function.client.DefaultWebClient: TRACE


server:
  port: 8080
  address: 127.0.0.1